class AuthError(Exception):
    pass


class NOConnect(Exception):
    pass
